openapi: 3.0.0
info:
  title: cash_control
  version: 1.0.0
servers:
  - url: https://webservice-cash-control-server.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: category
  - name: auth
  - name: wallet
paths:
  /category/{categoryId}:
    get:
      tags:
        - category
      summary: Get Category by ID
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - category
      summary: Update Category by ID
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                wallet_name: flip
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - category
      summary: Delete Category by ID
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /category:
    get:
      tags:
        - category
      summary: Get All Categories
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - category
      summary: Add Category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                wallet_name: Ovo
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/registration:
    post:
      tags:
        - auth
      summary: Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_name: todos
                email: todos@gmail.com
                password: 1qazxsw2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                usernameEmail: todos
                password: 1qazxsw2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /wallet/{walletId}:
    get:
      tags:
        - wallet
      summary: Get Wallet by ID
      parameters:
        - name: walletId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - wallet
      summary: Update Wallet by ID
      parameters:
        - name: walletId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                wallet_id: 2
                amount: 132040.39
                contact: 6285921240821
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - wallet
      summary: Delete Wallet by ID
      parameters:
        - name: walletId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /wallet:
    get:
      tags:
        - wallet
      summary: Get All Wallets
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - wallet
      summary: Insert Wallet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                wallet_id: 5
                amount: 130000
                contact: 6285921240821
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /wallet/user/{userId}:
    get:
      tags:
        - wallet
      summary: Get Wallets by User ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
